import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
export default defineSchema({
  dashboards: defineTable({
    owner: v.string(),
    wallet: v.string(),
    title: v.string(),
    payload: v.string(),
    updatedAt: v.number(),
  }).index("by_owner_wallet", ["owner", "wallet"]),
  preferences: defineTable({
    owner: v.string(),
    wallet: v.string(),
    payload: v.string(),
    message: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    approvedAt: v.optional(v.number()),
    signature: v.optional(v.string()),
  }).index("by_owner_wallet", ["owner", "wallet"]),
  payments: defineTable({
    owner: v.string(),
    wallet: v.string(),
    preferenceId: v.id("preferences"),
    payload: v.string(),
    amount: v.string(),
    status: v.union(
      v.literal("quoted"),
      v.literal("active"),
      v.literal("confirmed"),
      v.literal("cancelled"),
    ),
    createdAt: v.number(),
    expiresAt: v.number(),
    startedAt: v.optional(v.number()),
    step: v.number(),
    hashes: v.array(v.string()),
    issued: v.boolean(),
    pendingHash: v.optional(v.string()),
    delegationPolicyId: v.optional(v.string()),
    nonce: v.optional(v.number()),
    background: v.optional(v.boolean()),
    workerGeneration: v.optional(v.number()),
    workerAttempts: v.optional(v.number()),
    workerStep: v.optional(v.number()),
    workerJob: v.optional(v.id("_scheduled_functions")),
    workerState: v.optional(
      v.union(
        v.literal("queued"),
        v.literal("running"),
        v.literal("attention"),
        v.literal("done"),
      ),
    ),
    workerMessage: v.optional(v.string()),
  }).index("by_owner_wallet", ["owner", "wallet"]),
  snapshots: defineTable({
    owner: v.string(),
    wallet: v.string(),
    payload: v.string(),
    updatedAt: v.number(),
  }).index("by_owner_wallet", ["owner", "wallet"]),
  plans: defineTable({
    owner: v.string(),
    wallet: v.string(),
    payload: v.string(),
    status: v.union(
      v.literal("quoted"),
      v.literal("executing"),
      v.literal("confirmed"),
      v.literal("cancelled"),
    ),
    step: v.number(),
    hashes: v.array(v.string()),
    pendingHash: v.optional(v.string()),
    issued: v.optional(v.boolean()),
    nonce: v.optional(v.number()),
    createdAt: v.number(),
    expiresAt: v.number(),
  }).index("by_owner", ["owner"]),
  limits: defineTable({
    owner: v.string(),
    bucket: v.string(),
    start: v.number(),
    count: v.number(),
  }).index("by_owner_bucket", ["owner", "bucket"]),
});
